# Site settings
title: Your awesome title
email: ochoa.lopez.eugenio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eu271.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  eu271

# Build settings
markdown: kramdown

future: false # Previene por publicar contenido que tiene fecha futura.

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      draft: ""
      published: false
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      draft: "(Draft)"