# Site settings
title: Eugenio Ochoa
email: ochoa.lopez.eugenio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  News about my projects and my interests.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eu271.github.io/" # the base hostname & protocol for your site
github_username:  eu271
twitter_username: e2_71
deviantart_username: eu271


# Build settings
markdown: kramdown

future: false # Previene por publicar contenido que tiene fecha futura.

paginate: 25 # Posts per page

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "Eugenio Ochoa"
      language: "english"

  -
    scope:
      path: ""
      type: "drafts"
    values:
      draft: "(Draft)"

collections:
  owen:
    output: true
  designsprojects:
    output: true
