# Site settings
title: Eugenio
email: ochoa.lopez.eugenio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  News about my proyects and my interests. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eu271.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  eu271

# Build settings
markdown: kramdown

future: false # Previene por publicar contenido que tiene fecha futura.

paginate: 10 # Posts per page

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      draft: "(Draft)"